#!/usr/bin/env sh
# Regenerate the verbatim license texts for all Go modules compiled into mdoc.
#
# Uses google/go-licenses to walk the actual import graph of ./... so only the
# modules that end up in the binary are included. Output lands in licenses/go/.
#
# The bundled web assets under licenses/web/ are maintained by hand and are NOT
# touched by this script.
set -eu

TOOL="github.com/google/go-licenses@v1.6.0"
SELF_MODULE="github.com/hinkolas/mdoc"

ROOT="$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)"
cd "$ROOT"

echo "Saving Go dependency licenses into licenses/go/ ..."
rm -rf licenses/go
go run "$TOOL" save ./... \
  --save_path=licenses/go \
  --ignore "$SELF_MODULE" \
  --force

echo "Writing licenses/go/README.md ..."
{
  echo "# Go dependency licenses"
  echo
  echo "Generated by \`scripts/gen-licenses.sh\` using [go-licenses](https://github.com/google/go-licenses)."
  echo "Do not edit by hand — rerun the script after changing dependencies."
  echo
  echo "The verbatim license text for each module lives next to this file, under a"
  echo "directory matching the module's import path. Modules whose license ships a"
  echo "\`NOTICE\` file have it saved alongside the license."
  echo
  echo "| Package | License | Source |"
  echo "| ------- | ------- | ------ |"
  go run "$TOOL" report ./... --ignore "$SELF_MODULE" 2>/dev/null \
    | sort -t, -k1 \
    | awk -F, '{ printf "| %s | %s | %s |\n", $1, $3, $2 }'
} > licenses/go/README.md

echo "Done. Review changes under licenses/go/ before committing."
